version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway
      POSTGRES_DB: gateway
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway -d gateway"]
      interval: 5s
      timeout: 2s
      retries: 20

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 20

  gateway:
    image: 4runr/gateway:dev
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - config/.env
    environment:
      - UPSTREAM_MODE=${UPSTREAM_MODE:-mock}
      - FF_CHAOS=${FF_CHAOS:-off}
    ports: ["3000:3000"]
    # Add memory limits to prevent container from consuming all host memory
    mem_limit: 1.5g
    mem_reservation: 512m
    # Add restart policy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/ready"]
      interval: 10s
      timeout: 2s
      retries: 12
