services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: 4runr-postgres
    environment:
      POSTGRES_DB: 4runr_gateway
      POSTGRES_USER: 4runr
      POSTGRES_PASSWORD: 4runr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 4runr -d 4runr_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - 4runr-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: 4runr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - 4runr-network

  # 4Runr Gateway API
  gateway:
    build:
      context: ../apps/gateway
      dockerfile: Dockerfile
    container_name: 4runr-gateway
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ../apps/gateway:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - 4runr-network

  # SSE Worker for Guard/Audit events
  sse-worker:
    build:
      context: ../apps/sse-worker
      dockerfile: Dockerfile
    container_name: 4runr-sse-worker
    environment:
      - NODE_ENV=development
    volumes:
      - ../apps/sse-worker:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - 4runr-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: 4runr-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - 4runr-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  4runr-network:
    driver: bridge
